### ISSUE TITLE
build: add py3.12, remove py3.8; use Debian 12

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#199]
- [ ] #225 Add support for py3.12
- [x] #224 Remove support for py3.8 (end of life: [2024-10](https://devguide.python.org/versions/))
- [x] #226 Use Python images built based on Debian Bookworm (v12) instead of Debian Bullseye (v11; end of life: [2024-07](https://devguide.python.org/versions/))

**Comment by uniqueg** [comment]
Closing this because we now have individual issues.
