### ISSUE TITLE
Inventory of common code

### ISSUE THREAD

**Issue by sarthakgupta072** [elixir-cloud-aai/foca#5]
##### Add list items here:

- [x] - `api.register_openapi`
- [x] - `config.config_parser`
- [x] - `config.log_config`
- [x] - `database.db_utils`
- [x] - `errors.errors`
- [x] - `factories.celery_app`
- [x] - `factories.connexion_app`
- [x] - `security.cors`
- [x] - `security.decorators`
- [x] - `Dockerfile`

**Note for Contributors:** While adding the common modules, please write unit tests along with them; let's shoot for 100% coverage.

**Comment by uniqueg** [comment]
Looks good. Probably a good idea to start with the config parser (you can open an issue for that). Not sure whether we should include any of the Celery stuff, at least not at this point. Do you know if the authorization decorators are in any of these modules? Because those should for sure also go into the archetype.

**Comment by sarthak-sopho** [comment]
>  Do you know if the authorization decorators are in any of these modules? Because those should for sure also go into the archetype.
I'll update the list as soon as I find them.

**Comment by sarthak-sopho** [comment]
#10 - Add database module(s)

**Comment by sarthak-sopho** [comment]
https://github.com/elixir-cloud-aai/foca/issues/25 - Add security package module(s)

**Comment by sarthakgupta072** [comment]
https://github.com/elixir-cloud-aai/foca/issues/31 - Add factories module(s)

**Comment by kushagra189** [comment]
#41  - Add tasks module(s)

**Comment by uniqueg** [comment]
#34 - Add Dockerfile

**Comment by uniqueg** [comment]
#40 - Add OpenAPI registration

**Comment by uniqueg** [comment]
We are pretty much done, but I think there are a few more utils, like a decorator to log requests/responses that is very much general use, so will give the cwl-WES etc. codebases another scan before closing this.

**Comment by uniqueg** [comment]
Will close the issue:

* The decorator for logging requests and responses has been implemented (#76).
* A pass through cwl-WES etc. did not reveal any other code blocks for general use, except for generating random identifiers, which has been implemented (#84).
* A separate issue has been opened for setting environment variables in the config (#59) but will likely not be implemented without a concrete use case driving it.
* For Gunicorn support, a separate issue has been opened (#86)
