### ISSUE TITLE
Test FOCA in apps that don't yet rely on them

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/foca#91]
Replace boilerplate code with FOCA and test functionality in the following apps:

- [ ] [**cwl-WES**](https://github.com/elixir-cloud-aai/cwl-WES) (elixir-cloud-aai/cwl-WES#153)
- [x] [**proWES**](https://github.com/elixir-cloud-aai/proWES) (elixir-cloud-aai/proWES#10)
- [x] [**proTES**](https://github.com/elixir-cloud-aai/proTES) (elixir-cloud-aai/proTES#55)

Note that this is a metaissue that should remain open until all linked issues (see above) are closed.
